version: "3"
services:

   db:
     image: mysql:5.7
     volumes:
       - ./db-service/config:/etc/mysql/conf.d
       - ./db-service/sql:/docker-entrypoint-initdb.d
     ports:
       - "3306:3306"
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

   blog-service:
     build: ./blog-service
     depends_on:
       - db
     ports:
       - "5000:5000"
