export default {
  // aboutme
  SET_ABOUT_ME: 'REPLACE_USER_INFO',
  // article
  SET_CURRNET_ARTICLE: 'SET_CURRNET_ARTICLE',
  SET_ARTICLE_LIST: 'SET_ARTICLE_LIST',
  NEXT_PAGE: 'NEXT_PAGE',
  SET_ACTIVE_ORDERBY: 'SET_ACTIVE_ORDERBY'
};
